# Organization Routes

librecores_project_repo_organization_index:
    path:     /o/
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:index }

librecores_project_repo_organization_list:
    path:     /o/list
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:list }

librecores_project_repo_organization_new:
    path:     /o/new
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:new }

librecores_project_repo_organization_settings:
    path:     /o/{organizationName}/settings
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:settings }

librecores_project_repo_organization_remove:
    path:     /o/{organizationName}/remove
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:remove }

librecores_project_repo_organization_search:
    path:     /o/search
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:search }

librecores_project_repo_organization_join:
    path:     /o/{organizationName}/join
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:join }

librecores_project_repo_organization_leave:
    path:     /o/{organizationName}/leave
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:leave }

librecores_project_repo_organization_requests:
    path:     /o/{organizationName}/requests
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:requests }

librecores_project_repo_organization_approve:
    path:     /o/{organizationName}/{userName}/approve
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:approve }

librecores_project_repo_organization_deny:
    path:     /o/{organizationName}/{userName}/deny
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:deny }

# Project Routes

librecores_project_repo_project_new:
    path:     /new
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:projectNew }

librecores_project_repo_project_view:
    path:     /{parentName}/{projectName}
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:projectView }

librecores_project_repo_project_settings:
    path:     /{parentName}/{projectName}/settings
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:projectSettings }

librecores_project_repo_project_settings_team:
    path:     /{parentName}/{projectName}/settings/team
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:projectSettingsTeam }

librecores_project_repo_project_search:
    path:     /search
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:projectSearch }

# Other Routes

librecores_project_repo_homepage:
    path:     /
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:index }

librecores_project_repo_user_org_view:
    path:     /{userOrOrganization}
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:userOrgView }
