services:
    # Consumer Services (called through RabbitMQ)
    update_project_info_service:
        class: Librecores\ProjectRepoBundle\Consumer\UpdateProjectInformation
        arguments:
            - '@librecores.repocrawlerfactory'
            - '@logger'
            - '@doctrine'

    # Utilities
    librecores.util.markuptohtmlconverter:
        class: Librecores\ProjectRepoBundle\Util\MarkupToHtmlConverter
        arguments:
            - '@logger'
            - '@exercise_html_purifier.default'

    librecores.repocrawlerfactory:
        class: Librecores\ProjectRepoBundle\RepoCrawler\RepoCrawlerFactory
        arguments:
            - '@librecores.util.markuptohtmlconverter'
            - '@logger'

    # Forms
    app.form.type.project:
        class: Librecores\ProjectRepoBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: project }

    app.form.type.organization:
        class: Librecores\ProjectRepoBundle\Form\Type\OrganizationType
        tags:
            - { name: form.type, alias: organization }

    librecores.form_extention.icon:
        class: Librecores\ProjectRepoBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

    librecores.form.type.purified_textarea:
        class: Librecores\ProjectRepoBundle\Form\Type\PurifiedTextareaType
        arguments:
          - '@librecores.form.transformer.html_purifier'
        tags:
            - { name: form.type, alias: purified_textarea }

    librecores.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments:
            - '@exercise_html_purifier.default'

    validator.user_org_name:
        class: Librecores\ProjectRepoBundle\Validator\Constraints\UserOrgNameValidator
        arguments:
            - '@doctrine'
            - '@router'
        tags:
            - { name: validator.constraint_validator }

    # User/auth management services
    librecores_user_manager:
        class: Librecores\ProjectRepoBundle\Doctrine\UserManager
        arguments: ['@fos_user.util.password_updater', '@fos_user.util.canonical_fields_updater', '@fos_user.object_manager', '%fos_user.model.user.class%']

    librecores_user_provider:
        class: Librecores\ProjectRepoBundle\Security\Core\User\LibreCoresUserProvider
        arguments:
            - '@fos_user.user_manager'

    # Security
    librecores_project_voter:
        class: Librecores\ProjectRepoBundle\Security\ProjectVoter
        tags:
            - { name: security.voter }
        public: false

