---
# general site
- name: Create fresh librecores MySQL database
  command: mysql -u root -e "DROP DATABASE IF EXISTS librecores; CREATE DATABASE librecores CHARACTER SET = utf8 COLLATE utf8_general_ci;"

- name: Add librecores user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON librecores.* TO 'librecores'@'%'; FLUSH PRIVILEGES;"

- name: Create Symfony configuration
  template: src=parameters.yml dest=/var/www/site/app/config/parameters.yml

- name: Install dependencies through composer
  command: composer install
  args:
    chdir: /var/www/site

- name: Let doctrine generate DB contents
  command: php app/console doctrine:schema:update --force
  args:
    chdir: /var/www/site

- name: Import LibreCores development DB Dump
  shell: mysql -u librecores librecores < /var/www/sql/dev_fixtures_site.sql


# wordpress blog
- name: Create librecores-blog MySQL database
  command: mysql -u root -e "DROP DATABASE IF EXISTS `librecores-blog`; CREATE DATABASE `librecores-blog` CHARACTER SET = utf8 COLLATE utf8_general_ci;"

- name: Add librecores-blog user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON `librecores-blog`.* TO 'librecores-blog'@'%'; FLUSH PRIVILEGES;"

- name: Import LibreCores development DB Dump
  shell: mysql -u librecores-blog librecores-blog < /var/www/sql/dev_fixtures_blog.sql
