imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    default_locale:  "%locale%"
    #translator:      { fallback: en }
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../sitecontent": site_content
    form:
        # Use Bootstrap Form styling by default
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        # JavaScript files loaded inside <head> (only for special cases)
        js_head:
            inputs:
                - "js/respond.min.js"
                - "js/html5shiv.min.js"

        # JavaScript files loaded at the bottom of <body> (preferred)
        js_body_end:
            inputs:
                - "js/jquery.min.js"
                - "js/bootstrap.min.js"
                - "js/bootstrap-markdown.js"
                - "js/markdown.min.js"
                - "js/moment.min.js"
                - "js/livestamp.js"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# SimplePie (RSS/Atom Parser) Configuration
# Docs: http://simplepie.org/wiki/faq/how_does_simplepie_s_caching_http_conditional_get_system_work
fkr_simple_pie:
    cache_enabled: true
    cache_dir: %kernel.cache_dir%/rss
    cache_duration: 3600

# RabbitMQ Configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     %rabbitmq_port%
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: direct}
    consumers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: direct}
            queue_options:    {name: 'update-project-info'}
            callback:         update_project_info_service

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Librecores\ProjectRepoBundle\Entity\User
    service:
        user_manager: librecores_user_manager

# HWI OAuth Configuration
hwi_oauth:
    connect:
        confirmation: true
        account_connector: librecores_user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            github: oauth_user_id
            google: oauth_user_id
    resource_owners:
        github:
            type:                github
            client_id:           "%github_app_id%"
            client_secret:       "%github_app_secret%"
            scope:               "user:email"
            options:
                csrf:            true
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
#            paths:
#                email:           email
#                profilepicture:  picture
            options:
#                access_type:     offline
                display:         popup

