librecores_project_repo:
    resource: "@LibrecoresProjectRepoBundle/Resources/config/routing.yml"
    prefix:   /projects

librecores_site:
    resource: "@LibrecoresSiteBundle/Resources/config/routing.yml"
    prefix:   /
