---
- name: Create librecores MySQL database
  mysql_db: name=librecores state=present collation=utf8mb4_unicode_520_ci encoding=utf8mb4

- name: Add librecores@localhost user to MySQL
  mysql_user: name=librecores password={{ site_mysql_password }} priv=librecores.*:ALL host='localhost' state=present

- name: Add librecores@% user to MySQL
  mysql_user: name=librecores password={{ site_mysql_password }} priv=librecores.*:ALL host='%' state=present
