---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mysql-server state=installed

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: remove the test database
  mysql_db: name=test state=absent

- include: librecores-site.yml

- include: librecores-blog.yml
