librecores_core_repo:
    resource: "@LibrecoresCoreRepoBundle/Resources/config/routing.yml"
    prefix:   /cores

librecores_site:
    resource: "@LibrecoresSiteBundle/Resources/config/routing.yml"
    prefix:   /
