librecores_site_page:
    path:     /
    defaults: { _controller: LibrecoresSiteBundle:Default:home }

    path:     /{page}
    defaults: { _controller: LibrecoresSiteBundle:Default:page }
    requirements:
        # allow / inside path
        page: .+
