---
- name: Let doctrine generate DB contents
  command: php app/console doctrine:schema:update --force
  args:
    chdir: /var/www/site

- name: Import LibreCores development DB Dump
  mysql_db: >
    name=librecores
    login_user=librecores
    login_password={{ site_mysql_password }}
    state=import
    target=/var/www/sql/dev_fixtures_site.sql
