---
# PHP version to be used
# Packages are expected to be named php<php_version>, e.g. php7.0, php7.0-xml,
# etc. The same is true for the binaries.
php_version: 7.0

# PHP extensions, installed from OS packages (preferred)
# All packages are expected to be named "php{{ php_version }}-EXTENSION_NAME"
php_extensions_packaged:
  - dev
  - curl
  - mcrypt
  - mysql
  - xml
  - bcmath
  - mbstring
  - zip

# PHP extensions, installed through PEAR (if not available through OS packages)
php_extensions_pecl: []
#  - { name: "NAME", package: "pecl.php.net/NAME" }

# PHP FPM socket (for web servers)
php_fpm_sock: "/var/run/php/php{{ php_version }}-fpm.sock"
