---
# Install librecores planet generator
- name: Install extra packages for librecores-planet
  apt:  pkg={{ item }} state=installed
  with_items:
    - python-libxslt1

- name: Update planet every 30 minutes through cronjob
  cron:
    minute="*/30" hour="*" weekday="*"
    name="Update Planet LibreCores"
    cron_file="librecores-planet-update"
    user="{{ web_user }}"
    job="/var/www/planet/generate.sh"

